-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Oct 24, 2018 at 01:44 PM
-- Server version: 5.5.57-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `comp591`
--

-- --------------------------------------------------------

--
-- Table structure for table `artworks2`
--

CREATE TABLE IF NOT EXISTS `artworks2` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL DEFAULT '',
  `artist` varchar(50) NOT NULL DEFAULT '',
  `yearOfWork` varchar(20) DEFAULT NULL,
  `Information` text NOT NULL,
  `lat` double DEFAULT NULL,
  `long` double DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `locationNotes` varchar(200) DEFAULT NULL,
  `fileName` varchar(100) DEFAULT NULL,
  `lastModified` datetime DEFAULT '0000-00-00 00:00:00',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=65 ;

--
-- Dumping data for table `artworks2`
--

INSERT INTO `artworks2` (`id`, `title`, `artist`, `yearOfWork`, `Information`, `lat`, `long`, `location`, `locationNotes`, `fileName`, `lastModified`, `enabled`) VALUES
(34, 'Entrance', 'Maurice Cockrill', '1975', 'Hyper-realistic style painting of the artist''s girlfriend at the time outside what was the entrance to the Arts Reading Room.  Cockrill was a lecturer in fine art at Liverpool Polytechnic 1967-80 and Keeper of the Royal Academy of Arts, 2004.  He has been described as ''one of the most expressive painters of the 1980s and 1990s''.', 53.40191, -2.96588, 'Rendall Building', 'Entrance to the Rendall Building', 'Entrance by Maurice Cockrill.jpg', '2017-12-01 16:33:56', 1),
(35, 'The New Testament Group', 'Albrecht Lipczinski', '1915', 'This classical style group painting was commissioned by Professor Charles Reilly (Professor of Architecture) in 1915.  To pay for the commission Reilly collected a contribution from each of the professors involved.  The group shows senior members of the faculty who used to meet at the University Club and, though there was a claim that a missing portrait had been scraped out of the painting, technical analysis has proved this claim to be inconclusive.', 53.406733, -2.966015, 'Harold Cohen Library', 'In the reading/study room at the Harold Cohen Library, above glass doors', 'The New Testament Group by Lipczinski.jpg', '2017-12-01 16:34:05', 1),
(36, 'Composition', 'Henry Mundy', '1965', 'Mundy was born in Birkenhead in 1919.  He studied in Liverpool but now lives, works and teaches part time in Devon.  Mundy creates geometric compositions in an abstract style with acrylic on canvas or paper that do not refer to ''outside stimuli''.  This work was purchased when the artist was relatively unknown.  ', 53.406231, -2.965867, 'Electrical Engineering and Electronics', 'Electrical Engineering Building', 'Composition by Henry Mundy.jpg', '2017-12-01 16:34:17', 1),
(37, 'Wardrop I', 'Robyn Denny', '1961', 'This work was acquired when the artist was comparatively unknown.  His work has come to be represented in Tate Gallery, Museum of Modern Art (MOMA) and across the globe.  Denny was an abstract painter who was involved in transforming British art in the 1950s, leading it into the international mainstream.', 53.406231, -2.965867, 'Electrical Engineering and Electronics', 'Electrical Engineering Building', 'Wardrop 1 by Robyn Denny.jpg', '2017-12-01 16:34:23', 1),
(38, 'Enclosed Forms Brown and Blue', 'Paul Feiler', '1965', 'Born in Germany in 1919 Feiler came to England in 1933 where he studied at the Slade School of Fine Art and began his career as an artist in Britain.  From 1941 to 1975 he taught art in south west England.  He was inspired by the Cornish light and landscape.  His work is concerned with architectural space and organised geometric forms.', 53.406231, -2.965867, 'Electrical Engineering and Electronics', 'Electrical Engineering Building', 'Enclosed Forms by Paul Feiler.jpg', '2017-12-01 16:34:24', 1),
(39, 'Garrick No.2', 'Bernard Cohen', '1964', 'Cohen was born in London in 1933.  He studied at the Slade School of Fine Art from 1951 until 1954 and was appointed Professor and Director of the Slade in 1988.  His work became prominent in the 1960s and he has exhibited widely.  Cohen''s work displays complex images of pattern and colour with roots in abstract expressionism.  ', 53.406231, -2.965867, 'Electrical Engineering and Electronics', 'Electrical Engineering Building', 'Garrick No2 by Bernard Cohen.jpg', '2017-12-01 16:34:25', 1),
(40, 'Abstract', 'Christopher Darton Watkins', '1964', 'Watkins studied at the Ruskin School of Art, Oxford.  Over time he has developed his own techniques, building up the surface of the painting using different materials and incorporating beeswax, therefore removing the need to varnish his paintings and also enhancing the colours. ', 53.406231, -2.965867, 'Electrical Engineering and Electronics', 'Electrical Engineering Building', 'Abstract by Christopher Darton Watkins.jpg', '2017-12-01 16:34:27', 1),
(41, 'Sangaree', 'John Howlin', '1964', 'Howlin is known for his abstract images and use of vibrant colour.  This work shows the contrast between the matt and shiny surface as the artist uses plastic paint.  ', 53.406231, -2.965867, 'Electrical Engineering and Electronics', 'Electrical Engineering Building', 'Sangaree by John Howlin.jpg', '2017-12-01 16:34:28', 1),
(42, 'Umbro-Sienese', 'Trevor Bell', '1960', 'Born in Leeds in 1930 Bell studied at Leeds College of Art and became a leading member of a group of modernist artists working out of St Ives, Cornwall in the 1950s.  He was inspired by the interaction of elements and movmenet in nature.', 53.406231, -2.965867, 'Electrical Engineering and Electronics', 'Electrical Engineering Building', 'Umbro Sienese by Trevor Bell.jpg', '2017-12-01 16:34:29', 1),
(43, 'Far Shore', 'Bryan Wynter', '1963', 'Wynter''s style has progressed from figurative to a more dynamic abstract style.  His works are in many collections including the Tate, the British Council, the Arts Council and many other galleries across the UK.', 53.406231, -2.965867, 'Electrical Engineering and Electronics', 'Electrical Engineering Building', 'Far Shore by Bryan Wynter.jpg', '2017-12-01 16:34:30', 1),
(44, 'A Sunny Day', 'Endre Nemes', '1964', 'Nemes was born in Hungary and studied at the Art Academy in Prague.  He first exhibited in Prague in 1936 before he immigrated to Helsinki in 1938.  His work is represented in many public collections including the Museum of Modern Art Stockholm, Philadelphia Museum and Brooklyn Museum USA.', 53.406231, -2.965867, 'Electrical Engineering and Electronics', 'Electrical Engineering Building', 'A Sunny Day by Endre Nemes.jpg', '2017-12-01 16:34:36', 1),
(45, 'Statue of the Duke of Albany', 'Count Victor Gleichen', '1886', 'This sculpture of the Duke of Albany, youngest son of Queen Victoria and Prince Albert, shows him in his academic gown holding a closed book with a pile of books behind his left book.  The artist was his cousin.', 53.406389, -2.96739, 'Mechanical Engineering Building', 'Mechanical Engineering Building', 'Duke of Albany by Gleichen.png', '2017-12-05 09:27:37', 1),
(46, 'Figures', 'William Birnie Rhind', '1912-1914', 'The two figures are in full relief and are arranged around an urn, which shows similarities to the Greek style of C.J. Allen''s relief of Physiology and Pathology nearby.  The two figures are resting either side of the pediment, clasping their cloaks and gazing across the quadrangle.', 53.406561, -2.966203, 'Ashton Building', 'Front of the Ashton Building', 'Figures by Rhind.png', '2017-12-01 16:34:44', 1),
(47, 'Physiology and Pathology Relief', 'C.J. Allen', '1895-1898', 'This panel symbolises the medical research to be undertaken at the department of Physiology and Pathology.  The figures in the Greek style were modelled on the wives of Professor Sherrington who taught Physiology and Professor Boyce who taught Pathology.  Allen taught sculpture at the University until his retirement in 1927.', 53.406904, -2.967188, 'Thompson Yates Building', 'Front of the Thompson Yates Laboratory', 'Physiology and Pathology by Allen.png', '2017-12-01 16:34:51', 1),
(48, 'Learning', 'Eric Kennington', '1938', 'The figure holds a key and a lantern, the symbols of learning and stands before a large open book.  Kennington studied at the Lambeth School of Art in 1905 and served as a soldier in the First World War when he became an official war artist.  He is said to have taken up sculpture more or less by accident after being asked to recommend a sculptor for a war memorial and deciding to do the job himself.', 53.406733, -2.966015, 'Harold Cohen Library', 'Front of the Harold Cohen Library', 'Learning by Kennington.png', '2017-12-01 16:35:41', 1),
(49, 'War Memorial', 'C.J. Allen', 'Unveiled 1927', 'This sculpture occupies the space in the bay beneath the window in an ''altar-like'' arrangement.  Across the triptych are eight inscription tablets of French marble recording the 205 names of members of the University who sadly lost their lives in the First World War.  Above the central panel are the University Arms supported by a ''putto'' (little boy) holding a drooping palm branch.', 53.406228, -2.96616, 'Victoria Gallery & Museum', 'Victoria Gallery & Museum, Waterhouse Café near the clock', 'War Memorial by Allen.png', '2017-12-01 16:36:32', 1),
(50, 'Memorial to Charles William Jones', 'C.J. Allen', '1910', 'This work comprises a triptych of coloured alabaster with an oval white marble bas-relief portrait in the centre.  Jones was described as a great friend to the University and its students and taught sculpture here until his retirement in 1927.', 53.406228, -2.96616, 'Victoria Gallery & Museum', 'Victoria Gallery & Museum, on staircase leading up to the first floor', 'Memorial to Charles William Jones by Allen.png', '2017-12-01 16:36:33', 1),
(51, 'Statue of Christopher Bushell', 'Albert Bruce-Joy', 'Unveiled 1885', 'Bushell (1810-1887) was a distinguished public servant in the field of education and was one of the Trustees of Liverpool University College and one of the first Vice Presidents.  A memorial scholarship was set up in his name and this statue was unveiled in 1884 by the Archbishop of York.  The Victoria Building incorporated an apse for the statue and it was placed there shortly after the building''s completion in 1892.', 53.406228, -2.96616, 'Victoria Gallery & Museum', 'Victoria Gallery & Museum, Waterhouse Café', 'Christopher Bushell by Bruce-Joy.png', '2017-12-01 16:36:34', 1),
(52, 'Ouch', 'Stephen Hitchin', '2010', 'This sculpture was purchased from the artist after it was exhibited in ''As Long As It Takes'', an exhibition at the Victoria Gallery & Museum from 2009 to 2010.  Hitchin was born in Liverpool in 1953 and continues to work in studios in the city.', 53.406228, -2.96616, 'Victoria Gallery & Museum', 'Victoria Gallery & Museum, on staircase leading up to the first floor', 'Ouch by Hitchin.png', '2017-12-01 16:36:37', 1),
(53, 'Open Metalwork Gate and Screen', 'John McCarthy', '1961', 'The gate and screen are both inspired by mathematics and are abstract in design.  The two elements of the work contrast one another.  The gate consists of a star-like pattern of intersecting lines in thin wire and the screen is bolder, consisting of a free arrangement of mathematical symbols.  The sculptor continued the ideas of the building''s architect, who had intentionally used materials during construction that had contrasts in textures and light and dark materials.', 53.405383, -2.965423, 'Maths and Oceanography Building', 'Outside the Maths and Oceanography Building surrounding the bike park area', 'Open Metalwork by McCarthy.png', '2017-12-05 09:27:49', 1),
(54, 'Black Concrete Wall Relief', 'Eric Paskett', '', 'This relief comprises three unequal panels that span from the floor to the ceiling.  The design by Paskett is based on oceanographical motifs.  The black sculptured concrete proviesa contrast of between the plain, smooth surfaces and the rugged, sculptured ones.', 53.405379, -2.964723, 'Maths and Oceanography Building', 'Maths and Oceanography Building, near reception', 'Black Concrete Wall Relief by Paskett.png', '2017-12-01 16:37:04', 1),
(55, 'Five Panel Terracotta Mural', 'John McCarthy', '', 'These panels illustrate the growth of mathematical ideas and were designed by McCarthy.  ', 53.405379, -2.964723, 'Maths and Oceanography Building', 'Maths and Oceanography Building, over the lecture theatre doors and down the stairs', 'Five Panel Terracotta Mural by McCarthy.png', '2017-12-01 16:37:05', 1),
(56, 'Lettering', 'Maxwell Fry', '1960', 'The names of famous engineers are displayed in pre-cast concrete on a curved wall.  Fry is regarded as the father of the modern movement in architecture in Britain and he believed that buildings should be carefully matched to their environment.  Fry trained at Liverpool School of Architecture.', 53.406817, -2.968322, 'Civil Engineering Building', 'Front of the Maxwel Fry/Civil Engineering Building', 'Lettering by Fry.png', '2017-12-05 09:28:08', 1),
(57, 'Conflict of Man with the Tides and the Sands', 'Peter Lanyon', '1960', 'This work was commissiond for its relevance to the work on tidal barrages and erosion undertaken in the Civil Engineering Department.  Lanyon took up gliding in order to get better acquainted with the landscape.  Tragically he died in 1964 from injuries sustained in a gliding accident.', 53.406668, -2.968232, 'Civil Engineering Building', 'Civil Engineering Building entrance', 'Conflict of Man by Lanyon.png', '2017-12-05 09:28:12', 1),
(58, 'Memorial George Holt', 'George Frampton', '1897', 'George Holt was a ship owner and leading benefactor of University College, the former name for the University of Liverpool.  He and his brothers also gave Wavertree Park to Liverpool in 1895.', 53.406228, -2.96616, 'Victoria Gallery & Museum', 'Victoria Gallery & Museum, stairs leading to the second floor', 'Memorial George Holt by Frampton.png', '2017-12-01 16:36:39', 1),
(59, 'Red Between', 'Philip King', '1971-1973', 'Red Between was made in two stages over two years, separated by the making of ''Yellow Between'' and ''Blue Between''.  Red Between is described as having common elements with the other works but seems less composed and has less ''skin-like'' paint effects than the other works.', 53.406792, -2.966819, 'VGM Quadrangle', 'Quadrangle behind Victoria Gallery & Museum', 'Red Between by King.png', '2017-12-04 09:31:12', 1),
(60, 'Liverpool Heroes Memorial Statue', 'Tom Murphy', '2008', 'This bronze statue was unveiled in 2008 and is dedicated to war hero Captain Noel Chavasse who died in 1914.  Chavasse was the only man to be awarded two Victoria Crosses during the First World War.  The memorial also names fifteen other Victoria Cross recipients who were born in Liverpool and sacrificed themselves in the First World War.', 53.403219, -2.965829, 'Abercromby Square', 'Abercromby Square', 'Liverpool Heroes by Murphy.png', '2017-12-04 09:30:56', 1),
(61, 'Shemaiah', 'Sean Rice', '1980s', 'Rice was a unique and innovative Liverpool artist who both made works and taught at the Liverpool School of Art.  His wide ranging influences, which included oriental and primitive art, are often visible in his works.  He mainly made figurative work, many with religious themes.  Shemaiah is a prophet from the Old Testament.', 53.406593, -2.967644, 'VGM Quadrangle', 'Quadrangle behind Victoria Gallery & Museum', 'Shemaiah by Rice.png', '2017-12-04 09:31:16', 1),
(62, 'Square With Two Circles', 'Barbara Hepworth', '1964', 'Dame Jocelyn Barbara Hepworth DBE was an English artist and sculptor.  Her work exemplifies Modernism and in particular modern sculpture.  She was one of the few female artists of her generation to achieve international prominence.  This sculpture is made of bronze with a concrete base.  Hepworth was influenced by the monolithic power of stone monuments and uses the cut out circles as a device to open up the solid mass of the structure.', 53.405944, -2.96237, 'Crown Place', 'Crown Place Halls of Residence', 'Square with Two Circles by Hepworth.png', '2017-12-01 16:37:20', 1),
(63, 'Gogglehead', 'Elisabeth Frink', '1967', 'This work is one of a series of oversize heads, originally conceived as soldiers.  Frink explained the works in relation to oppression at a time when she was actively interested in human rights and said "I always find it rather sinister when you can''t see people''s eyes".', 53.406228, -2.96616, 'Victoria Gallery & Museum', 'Victoria Gallery & Museum, first floor', 'Gogglehead by Frink.png', '2018-06-20 11:48:57', 1),
(64, 'Front Runner', 'Elisabeth Frink', '1987', 'Frink studied at the Guildford School of Art (1946-1947) and the Chelsea School of Art (1949-1953).  She was created a Dame of the British Empire in 1982.  She described this work as a tribute to human rights and that the figure is a man running away from persecution.', 53.40701, -2.967735, 'Whelan Quadrangle', 'Quadrangle between Whelan Building and Thompson Yates Laboratories', 'Front Runner by Frink.png', '2017-12-04 09:31:31', 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
